# Generated by Django 5.1.4 on 2025-01-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_initial'),
    ]

    operations = [
    ]
