# Generated by Django 5.1.4 on 2025-01-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_remove_stationprices_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationprices',
            name='currency',
            field=models.CharField(default='PLN', help_text='The currency of the purchase price.', max_length=3),
        ),
    ]
