# Generated by Django 5.1.4 on 2025-02-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_stationprices_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationprices',
            name='brand_name',
            field=models.CharField(choices=[('amic', 'Amic'), ('lotos', 'Lotos'), ('lotos optima', 'Lotos Optima'), ('circle-k', 'Circle-k'), ('bp', 'BP'), ('moya', 'Moya'), ('auchan', 'Auchan'), ('tesco', 'Tesco'), ('carrefour', 'Carrefour'), ('olkop', 'Olkop'), ('leclerc', 'Leclerc'), ('intermarche', 'Intermarche'), ('mol', 'MOL'), ('huzar', 'Huzar'), ('total', 'Total'), ('polska', 'Polska')], help_text='Select the fuel station brand.', max_length=20),
        ),
    ]
