# Generated by Django 5.1.4 on 2025-01-24 11:53

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0003_alter_trip_user_alter_vehicle_data_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicle_data',
            name='cur_fuel_lte_tank_size',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='refill_number',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='refill_price',
        ),
        migrations.RemoveField(
            model_name='tripnode',
            name='destination_address',
        ),
        migrations.RemoveField(
            model_name='tripnode',
            name='origin_address',
        ),
        migrations.RemoveField(
            model_name='tripnode',
            name='trip_price',
        ),
        migrations.RemoveField(
            model_name='vehicle_data',
            name='cur_fuel',
        ),
        migrations.RemoveField(
            model_name='vehicle_data',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='vehicle_data',
            name='price_of_fuel',
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tripnode',
            name='bought_gas_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of bought fuel at the beginning of node. Per liter', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='tripnode',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='tripnode',
            name='fuel_refilled',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Fuel added at the beggining of the node', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='tripnode',
            name='origin',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='vehicle_data',
            name='need_refill',
            field=models.BooleanField(blank=True, help_text='Information wheter the vehicle needs refill.', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_data',
            name='fuel_consumption_per_100km',
            field=models.DecimalField(decimal_places=2, help_text="The vehicle's fuel consumption in liters per 100 kilometer.", max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='vehicle_data',
            name='fuel_type',
            field=models.CharField(choices=[('D', 'Diesel'), ('PB95', 'PB95'), ('LPG', 'LPG'), ('PB98', 'PB98')], help_text='The type of fuel used by the vehicle.', max_length=4),
        ),
    ]
