# Generated by Django 5.1.4 on 2025-01-27 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0004_remove_vehicle_data_cur_fuel_lte_tank_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripnode',
            name='duration',
        ),
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Duration of the trip - in minutes', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='vehicle_data',
            name='need_refill',
            field=models.BooleanField(default=False, help_text='Information wheter the vehicle needs refill.'),
        ),
    ]
