# Generated by Django 5.1.4 on 2025-01-30 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0005_remove_tripnode_duration_trip_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='duration',
        ),
        migrations.AddField(
            model_name='tripnode',
            name='duration',
            field=models.DecimalField(decimal_places=1, help_text='Duration of the trip - in minutes', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='tripnode',
            name='distance',
            field=models.DecimalField(decimal_places=1, help_text='Distance of trip', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
