# Generated by Django 5.1.4 on 2025-01-30 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0008_alter_tripnode_distance_alter_tripnode_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripnode',
            name='fuel_refilled',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel added at the beggining of the node', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
