# Generated by Django 5.1.4 on 2025-01-31 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0009_alter_tripnode_fuel_refilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_data',
            name='tank_size',
            field=models.FloatField(help_text="The size of the vehicle's fuel tank in liters.", validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
