# Generated by Django 5.1.4 on 2025-02-03 10:59

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0010_alter_vehicle_data_tank_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination_address',
            field=models.CharField(blank=True, help_text='The ending address of the trip.', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='first_trip_node',
            field=models.ForeignKey(default=None, help_text='The first node of the trip.', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='refill.tripnode'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='guest_session_id',
            field=models.CharField(blank=True, help_text='Session identifier for guest users.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin_address',
            field=models.CharField(blank=True, help_text='The starting address of the trip.', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who owns this trip.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tripnode',
            name='bought_gas_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel price per liter at the beginning of this node.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='tripnode',
            name='currency',
            field=models.CharField(default='PLN', help_text='Currency code for any monetary values in this node.', max_length=3),
        ),
        migrations.AlterField(
            model_name='tripnode',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='The ending geographic point for this trip node.', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='tripnode',
            name='distance',
            field=models.DecimalField(decimal_places=1, help_text='Distance covered in this trip node.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='tripnode',
            name='duration',
            field=models.DecimalField(decimal_places=1, help_text='Duration (in minutes) of this trip node.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='tripnode',
            name='fuel_refilled',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of fuel added (in liters) at the beginning of this node.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='tripnode',
            name='next_trip',
            field=models.ForeignKey(blank=True, help_text='The next trip node in the sequence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_node', to='refill.tripnode'),
        ),
        migrations.AlterField(
            model_name='tripnode',
            name='origin',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='The starting geographic point for this trip node.', null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_size', models.FloatField(help_text="The size of the vehicle's fuel tank in liters.", validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fuel_type', models.CharField(choices=[('D', 'Diesel'), ('PB95', 'PB95'), ('LPG', 'LPG'), ('PB98', 'PB98')], help_text='The type of fuel used by the vehicle.', max_length=4)),
                ('fuel_consumption_per_100km', models.DecimalField(decimal_places=2, help_text='Fuel consumption in liters per 100 kilometers.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('need_refill', models.BooleanField(blank=True, help_text='Indicates whether the vehicle needs a refill.', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='The owner of the vehicle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehicle used during this trip.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='refill.vehicledata'),
        ),
        migrations.DeleteModel(
            name='Vehicle_data',
        ),
    ]
