# Generated by Django 5.1.4 on 2025-02-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0011_alter_trip_destination_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('PB95', 'PB95'), ('LPG', 'LPG'), ('PB98', 'PB98')], help_text='The type of fuel used by the vehicle.', max_length=6),
        ),
    ]
