# Generated by Django 5.1.4 on 2025-02-08 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0012_alter_vehicledata_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripnode',
            name='distance',
            field=models.DecimalField(decimal_places=1, help_text='Distance covered in this trip node (in km).', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
