# Generated by Django 5.1.4 on 2025-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0013_alter_tripnode_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripnode',
            name='station_id',
            field=models.IntegerField(blank=True, help_text='Id of the station thats the origin', null=True),
        ),
    ]
