# Generated by Django 5.1.4 on 2025-02-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0014_tripnode_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledata',
            name='driving_conditions',
            field=models.CharField(blank=True, choices=[('City', 'City'), ('Mixed', 'Mixed'), ('Highway', 'Highway')], help_text='The typical driving conditions in which the fuel usage is given ', max_length=7, null=True),
        ),
    ]
