# Generated by Django 5.1.4 on 2025-02-17 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0015_vehicledata_driving_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripnode',
            name='bought_gas_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel price per liter at the beginning of this node.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
