# Generated by Django 5.1.4 on 2025-02-17 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0016_alter_tripnode_bought_gas_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripnode',
            name='fuel_refilled',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of fuel added (in liters) at the beginning of this node.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
